# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: gigamoji
builds:
  - id: default
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
    main: .
    binary: gigamoji
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    hooks:
      post:
        - make man VERSION={{.Version}} COMMIT={{.ShortCommit}} DATE={{.Date}}
brews:
  - install: |
      bin.install "gigamoji"
      man1.install Dir.glob('gigamoji*.1')
    tap:
      owner: kyoh86
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/kyoh86/gigamoji
    description: "generate emoji (like \U0001F44D in slack) banner which support some bitmap font faces"
    license: MIT
nfpms:
  - builds:
      - default
    maintainer: kyoh86 <me@kyoh86.dev>
    homepage: https://github.com/kyoh86/gigamoji
    description: "generate emoji (like \U0001F44D in slack) banner which support some bitmap font faces"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
archives:
  - id: gzip
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
      - gigamoji.1
